import type { Metadata } from 'next';
import { Roboto_Mono } from 'next/font/google';
import './globals.css';
import MainNavigation from '@/components/main-navigation';
import Footer from '@/components/footer';

const robotoMono = Roboto_Mono({ subsets: ['latin'] });

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        suppressHydrationWarning={true}
        className={robotoMono.className + ' container mx-auto flex flex-col'}>
        <MainNavigation />
        {children}
        <Footer />
      </body>
    </html>
  );
}
